# Generated by Django 6.0.5 on 2026-06-29 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0010_alter_tarefa_cabos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promessa',
        ),
    ]
