# Generated by Django 6.0.5 on 2026-06-30 22:21

from django.db import migrations, models

# Remapeia os "tipos" antigos (natureza da ação) para as novas ÁREAS (setores).
_MAP = {
    'comunicacao': 'comunicacao',
    'evento': 'eventos',
    'captacao': 'mobilizacao',
    'visita': 'mobilizacao',
    'articulacao': 'estrategico',
    'reuniao': 'estrategico',
    'outro': 'administrativo',
}


def _para_area(apps, schema_editor):
    Tarefa = apps.get_model('tarefas', 'Tarefa')
    for t in Tarefa.objects.all():
        novo = _MAP.get(t.tipo, 'administrativo')
        if novo != t.tipo:
            t.tipo = novo
            t.save(update_fields=['tipo'])


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0011_delete_promessa'),
    ]

    operations = [
        migrations.RunPython(_para_area, _noop),
        migrations.AlterField(
            model_name='tarefa',
            name='tipo',
            field=models.CharField(choices=[('financeiro', 'Financeiro'), ('administrativo', 'Administrativo'), ('comunicacao', 'Comunicação'), ('mobilizacao', 'Mobilização'), ('estrategico', 'Estratégico'), ('eventos', 'Eventos')], default='administrativo', max_length=20, verbose_name='Área'),
        ),
    ]
