# Generated by Django 6.0.5 on 2026-06-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_compromisso_apoiadores_alter_compromisso_cabos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisso',
            name='tipo',
            field=models.CharField(choices=[('reuniao', 'Reunião'), ('evento', 'Evento'), ('visita', 'Visita'), ('roteiro', 'Roteiro'), ('comicio', 'Comício'), ('entrevista', 'Entrevista'), ('viagem', 'Viagem'), ('pessoal', 'Pessoal'), ('outro', 'Outro')], max_length=15),
        ),
    ]
