# Generated by Django 6.0.5 on 2026-06-12 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0011_interacao_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apoiador',
            name='cargo',
            field=models.CharField(blank=True, choices=[('prefeito', 'Prefeito'), ('vice_prefeito', 'Vice-Prefeito'), ('vereador', 'Vereador'), ('presidente_diretorio', 'Presidente Diretório'), ('ex_politico', 'Ex-Político'), ('outro', 'Outro')], max_length=25, verbose_name='Cargo Político'),
        ),
        migrations.CreateModel(
            name='Egresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Redes Sociais')),
                ('cidade_nome', models.CharField(blank=True, max_length=150, verbose_name='Cidade (texto)')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('curso', models.CharField(blank=True, max_length=150)),
                ('instituicao', models.CharField(blank=True, max_length=150, verbose_name='Instituição')),
                ('situacao_curso', models.CharField(blank=True, max_length=50, verbose_name='Situação do Curso')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egressos_atualizados', to=settings.AUTH_USER_MODEL)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egressos_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egressos', to='liderancas.cidade', verbose_name='Cidade (SC)')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Egresso',
                'verbose_name_plural': 'Egressos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lassberg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cidade_nome', models.CharField(blank=True, max_length=150, verbose_name='Cidade (texto)')),
                ('estado', models.CharField(blank=True, max_length=30, verbose_name='Estado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lassbergs_atualizados', to=settings.AUTH_USER_MODEL)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lassbergs_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lassbergs', to='liderancas.cidade', verbose_name='Cidade (SC)')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lassberg',
                'verbose_name_plural': 'Lassberg',
                'ordering': ['nome'],
            },
        ),
    ]
