# Generated by Django 6.0.5 on 2026-06-12 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0012_apoiador_cargo_egresso_lassberg'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacaolog',
            name='egresso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='liderancas.egresso'),
        ),
        migrations.AddField(
            model_name='interacaolog',
            name='lassberg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='liderancas.lassberg'),
        ),
    ]
